export const ROUTES = {
  HOME: "/",
  ABOUT: "/ve-chung-toi",
  PRODUCT: "/san-pham",
  PLASTIC: "/in-an",
  FRAME: "/khung-anh",
  ALBUM: "/photobook",
  PRICE: "/bang-gia",
  BLOG: "/tin-tuc",
  LOGIN: "/dang-nhap",
  REGISTER: "/dang-ky",
  ACCOUNT: "/tai-khoan",
  APP_FRAME: "/app-frame",
  APP_ALBUM: "/app-album",
};
